baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Drew-S'
theme = "m10c"

[params]
    author = 'Drew Sommer'
    description = 'My personal site: Blog posts, coding, programming, and tech'
    avatar = '/avatar.png'

[[params.social]]
    icon = 'github'
    name = 'Github'
    url = 'https://github.com/Drew-S'

[[params.social]]
    icon = 'linkedin'
    name = 'Linkedin'
    url = 'https://www.linkedin.com/in/DrewLSommer/'

[[params.social]]
    icon = ''
    name = 'Personal'
    url = 'https://drew-s.github.io'

[menu]
[[menu.main]]
    identifier = 'cv'
    name = 'Résumé'
    url = 'about/cv'
    weight = -100